spring:
   application:
     name: Greet-Api
   boot:
    admin:
      client:
        url: http://localhost:1111/
server:
  port: 9091
#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'

